name: Check PHP with Composer and ECS

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2

        with:
          php-version: '8.3'
          extensions: mbstring, intl, zip
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-scripts

      - name: Run ECS (EasyCodingStandard)
        run: php vendor/bin/ecs check src

      - name: Run PHPUnit
        run: vendor/bin/phpunit
